version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PINATA_GATEWAY_TOKEN=${PINATA_GATEWAY_TOKEN}
      - PINATA_GATEWAY_URL=${PINATA_GATEWAY_URL}
      - PROVIDER_URL=${PROVIDER_URL}
      - PRIVATE_KEY=${PRIVATE_KEY}
